/*
Shows the number of audit logs generated by users daily.
SELECT CAST(Timestamp AS DATE) AS Date, COUNT(Id) AS LogCount FROM AuditLogs WHERE Timestamp BETWEEN @StartDate AND @EndDate GROUP BY Date
*/
namespace VirtualMachineLifecycle.Apps.Views;

public class UserActivityByAuditLogsLineChartView(DateTime startDate, DateTime endDate) : ViewBase
{
    public override object? Build()
    {
        var factory = UseService<VirtualMachineLifecycleContextFactory>();
        var chart = UseState<object?>((object?)null);
        var exception = UseState<Exception?>((Exception?)null);

        this.UseEffect(async () =>
        {
            try
            {
                var db = factory.CreateDbContext();

                var data = await db.AuditLogs
                    .Where(a => a.Timestamp >= startDate && a.Timestamp <= endDate)
                    .GroupBy(a => a.Timestamp.Date)
                    .Select(g => new
                    {
                        Date = g.Key.ToString("d MMM"),
                        LogCount = g.Count()
                    })
                    .ToListAsync();

                chart.Set(data.ToLineChart(
                    e => e.Date,
                    [e => e.Sum(f => (double)f.LogCount)],
                    LineChartStyles.Dashboard));
            }
            catch (Exception ex)
            {
                exception.Set(ex);
            }
        }, []);

        var card = new Card().Title("User Activity by Audit Logs").Height(Size.Units(80));

        if (exception.Value != null)
        {
            return card | new ErrorTeaserView(exception.Value);
        }

        if (chart.Value == null)
        {
            return card | new Skeleton();
        }

        return card | chart.Value;
    }
}