/*
This code was generated by an AI model for seeding a database using the Bogus library. 
When debugging read 'DataContext.cs' first to understand the structure of the database.
Your primary goal is to make the generated code compile and run successfully. 
If you fail you are allowed to regenerate the code and/or comment out functionality, but only as a last resort.
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bogus;
using Microsoft.EntityFrameworkCore;

namespace VirtualMachineLifecycle;

public class DataSeeder : IDataSeeder
{
    private readonly DataContext _context;

    public DataSeeder(DataContext context)
    {
        _context = context;
    }

    public async System.Threading.Tasks.Task SeedAsync()
    {
        var faker = new Faker();

        if (!await _context.Users.AnyAsync())
        {
            var userFaker = new Faker<User>()
                .RuleFor(u => u.Username, f => f.Internet.UserName())
                .RuleFor(u => u.UserTypeId, f => f.PickRandom(new[] { 1, 2 }))
                .RuleFor(u => u.CreatedAt, f => f.Date.Past(1))
                .RuleFor(u => u.UpdatedAt, (f, u) => f.Date.Between(u.CreatedAt, DateTime.UtcNow));

            var newUsers = userFaker.Generate(100);
            _context.Users.AddRange(newUsers);
            await _context.SaveChangesAsync();
        }

        var users = await _context.Users.ToArrayAsync();

        if (!await _context.Vms.AnyAsync())
        {
            var vmFaker = new Faker<Vm>()
                .RuleFor(v => v.Name, f => f.Commerce.ProductName())
                .RuleFor(v => v.VmStatusId, f => f.PickRandom(new[] { 1, 2 }))
                .RuleFor(v => v.ProviderId, f => f.PickRandom(new[] { 1, 2 }))
                .RuleFor(v => v.Tags, f => string.Join(", ", f.Lorem.Words(3)))
                .RuleFor(v => v.LastAction, f => f.Date.Past(1))
                .RuleFor(v => v.CreatedAt, f => f.Date.Past(1))
                .RuleFor(v => v.UpdatedAt, (f, v) => f.Date.Between(v.CreatedAt, DateTime.UtcNow));

            var newVms = vmFaker.Generate(50);
            _context.Vms.AddRange(newVms);
            await _context.SaveChangesAsync();
        }

        var vms = await _context.Vms.ToArrayAsync();

        if (!await _context.Snapshots.AnyAsync())
        {
            var snapshotFaker = new Faker<Snapshot>()
                .RuleFor(s => s.Name, f => f.Lorem.Word())
                .RuleFor(s => s.CreatedAt, f => f.Date.Past(1))
                .RuleFor(s => s.UpdatedAt, (f, s) => f.Date.Between(s.CreatedAt, DateTime.UtcNow));

            var newSnapshots = new List<Snapshot>();
            foreach (var vm in vms)
            {
                var snapshotCount = faker.Random.Int(1, 5);
                for (int i = 0; i < snapshotCount; i++)
                {
                    var snapshot = snapshotFaker.Generate();
                    snapshot.VmId = vm.Id;
                    snapshot.CreatedBy = faker.PickRandom(users).Id;
                    newSnapshots.Add(snapshot);
                }
            }

            _context.Snapshots.AddRange(newSnapshots);
            await _context.SaveChangesAsync();
        }

        var snapshots = await _context.Snapshots.ToArrayAsync();

        if (!await _context.AuditLogs.AnyAsync())
        {
            var auditLogFaker = new Faker<AuditLog>()
                .RuleFor(a => a.Timestamp, f => f.Date.Past(1))
                .RuleFor(a => a.Details, f => f.Lorem.Sentence());

            var newAuditLogs = new List<AuditLog>();
            foreach (var user in users)
            {
                var logCount = faker.Random.Int(1, 10);
                for (int i = 0; i < logCount; i++)
                {
                    var auditLog = auditLogFaker.Generate();
                    auditLog.UserId = user.Id;
                    auditLog.ActionId = faker.PickRandom(new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 });
                    auditLog.VmId = faker.Random.Bool() ? faker.PickRandom(vms).Id : null;
                    newAuditLogs.Add(auditLog);
                }
            }

            _context.AuditLogs.AddRange(newAuditLogs);
            await _context.SaveChangesAsync();
        }
    }
}